// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8aDhkjkw3BLlFHtXGcMQ2Dk0AfXMuKQ',
    appId: '1:764461740957:web:ee55b82bee4825b12ef574',
    messagingSenderId: '764461740957',
    projectId: 'fir-storage-c6431',
    authDomain: 'fir-storage-c6431.firebaseapp.com',
    storageBucket: 'fir-storage-c6431.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZHujc3zYiGcaERwkaPyWsx_54bjNX_Uc',
    appId: '1:764461740957:android:07cae3689ec6e4e62ef574',
    messagingSenderId: '764461740957',
    projectId: 'fir-storage-c6431',
    storageBucket: 'fir-storage-c6431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXaCwf_mMZQZz7Y584JIn359oDwrVx6ag',
    appId: '1:764461740957:ios:95e44e2dcc2ec59a2ef574',
    messagingSenderId: '764461740957',
    projectId: 'fir-storage-c6431',
    storageBucket: 'fir-storage-c6431.appspot.com',
    iosClientId: '764461740957-m5cprop6ks4lub8gmhduicbkive6ncbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirestorage',
  );
}
